#cloud-config
disable_root: true
timezone: Europe/Moscow
package_update: true
package_upgrade: true
apt:
  preserve_sources_list: true
  sources:
    elk.list:
      source: "deb https://mirror.yandex.ru/mirrors/elastic/8/ stable main"
      keyid: D27D666CD88E42B4

packages:
  - kibana

runcmd:
  - [ sh, -c, "echo 'server.host: 0.0.0.0' >> /etc/kibana/kibana.yml" ]
  - [ sh, -c, "echo 'elasticsearch.hosts: [http://192.168.30.3:9200]' >> /etc/kibana/kibana.yml" ]
  - [ systemctl, enable, kibana.service ]
  - [ systemctl, restart, kibana.service ]

users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLU08AWIPAFQ0vfXU3AxHZbyIREoxA1POpxofHkVBT2Q+daDdCKswyu2etTCa0VAHu2NVWireQqKeYkS1oDQpz4J2KC0r97UIp61MZpocRX657YqVfWBXc7m679b9kPAXhIBZ1v9vdOl+nd0KgXstSKN7FCwQxq4XCAUe/0r62qF2PmYiNbYzay1vSmmJEgae3hLHnGrO3m3CfVsY4c13qqon1YdfLkiw4NaXZoNg8tWFu06mH9k+v/iSWXZago+8KQZQUrVR0cBGvM1uR4Bc4RHB3lX1FuU5M5W/hxkmDmN51U7OdNk9x6Srl058MfkYa0UcrhRDr+Ksv36NzQY4V user@notebook
