#cloud-config
disable_root: true
timezone: Europe/Moscow
package_update: true
package_upgrade: true
apt:
  preserve_sources_list: true
  sources:
    nginx.list:
      source: "deb http://nginx.org/packages/mainline/ubuntu jammy nginx"
      keyid: ABF5BD827BD9BF62
    postgresql.list:
      source: "deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main"
      keyid: 7FCC7D46ACCC4CF8
    zabbix.list:
      source: "deb https://repo.zabbix.com/zabbix/6.5/ubuntu jammy main"
      keyid: 082AB56BA14FE591

packages:
  - nginx
  - php8.1-pgsql
  - postgresql
  - zabbix-agent2
  - zabbix-agent2-plugin-postgresql
  - zabbix-frontend-php
  - zabbix-nginx-conf
  - zabbix-server-pgsql
  - zabbix-sql-scripts
  - zabbix-web-service

write_files:
  - path: /etc/zabbix/web/zabbix.conf.php
    content: |
      <?php
      $DB['TYPE'] = 'POSTGRESQL';
      $DB['SERVER'] = 'localhost';
      $DB['DATABASE'] = 'zabbix';
      $DB['USER'] = 'zabbix';
      $DB['PASSWORD'] = 'zabbix';
    permissions: '0600'
    owner: www-data:www-data

runcmd:
  - [ sh, -c, "locale-gen ru_RU.UTF-8" ]
  - [ sh, -c, "rm /etc/nginx/conf.d/default.conf" ]
  - [ sh, -c, "usermod -a -G www-data nginx" ]
  - [ sh, -c, "sed -i 's/# DBPassword=/DBPassword=zabbix/' /etc/zabbix/zabbix_server.conf" ]
  - [ systemctl, enable, nginx.service, php8.1-fpm.service, postgresql.service, zabbix-agent2.service, zabbix-server.service, zabbix-web-service.service ]
  - [ systemctl, restart, nginx.service, php8.1-fpm.service, postgresql.service, zabbix-agent2.service, zabbix-server.service, zabbix-web-service.service]
  - sudo -u postgres psql -c "CREATE USER zabbix WITH PASSWORD 'zabbix';" 
  - sudo -u postgres createdb -O zabbix zabbix
  - zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix 

users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLU08AWIPAFQ0vfXU3AxHZbyIREoxA1POpxofHkVBT2Q+daDdCKswyu2etTCa0VAHu2NVWireQqKeYkS1oDQpz4J2KC0r97UIp61MZpocRX657YqVfWBXc7m679b9kPAXhIBZ1v9vdOl+nd0KgXstSKN7FCwQxq4XCAUe/0r62qF2PmYiNbYzay1vSmmJEgae3hLHnGrO3m3CfVsY4c13qqon1YdfLkiw4NaXZoNg8tWFu06mH9k+v/iSWXZago+8KQZQUrVR0cBGvM1uR4Bc4RHB3lX1FuU5M5W/hxkmDmN51U7OdNk9x6Srl058MfkYa0UcrhRDr+Ksv36NzQY4V user@notebook
